'use strict';
Object.defineProperty(exports, '__esModule', { value: !0 });
var rooster = require('roosterjs');
rooster.createEditorWithGui(document.getElementById('mainPane'), [
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
    'Pracownik.Imie',
]);
